name: ThothOS Phase-1 smoke + tracker

on:
  workflow_dispatch: {}
  # (Optional) uncomment to auto-run on edits to these paths
  # push:
  #   paths:
  #     - "docs/progress.yaml"
  #     - "kernel/**"
  #     - "tools/scripts/**"
  #     - ".github/workflows/progress.yml"

jobs:
  smoke-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow committing the updated tracker
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/scripts/requirements.txt || true

      - name: Make scripts executable
        run: |
          chmod +x tools/scripts/run_smoke.sh || true

      - name: Phase-1 smoke tests
        run: |
          bash tools/scripts/run_smoke.sh

      - name: Update tracker from docs/progress.yaml
        run: |
          python tools/scripts/update_tracker.py

      - name: Commit & push tracker if changed
        run: |
          set -eux
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/TRACKER.md || true
          git diff --cached --quiet || git commit -m "ci: update TRACKER.md via docs/progress.yaml"
          git push
