name: phase1-smoke-and-tracker
on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/progress.yml"
      - "docs/progress.yaml"

jobs:
  smoke-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Ensure folders
        shell: bash
        run: |
          mkdir -p tools/scripts docs

      - name: Seed docs/progress.yaml if missing (or show it)
        shell: bash
        run: |
          if [ ! -f docs/progress.yaml ]; then
            printf "IPC-1: 30\nIPC-4: 25\nSCHED-2: 20\n" > docs/progress.yaml
          fi
          echo "---- progress.yaml ----"
          cat docs/progress.yaml

      - name: Seed tools/scripts/run_smoke.sh if missing
        shell: bash
        run: |
          if [ ! -f tools/scripts/run_smoke.sh ]; then
            printf '#!/usr/bin/env bash\nset -euo pipefail\n' > tools/scripts/run_smoke.sh
            printf 'check_dir(){ [ -d "$1" ] || { echo "::error ::Missing $1"; exit 1; }; }\n' >> tools/scripts/run_smoke.sh
            printf 'for d in kernel/ipc kernel/sched kernel/pm kernel/security kernel/observability daemons/prom codex/vectorstore codex/memory_graph codex/timeline scrolls/engine scrolls/rituals bridges docs tools/scripts; do\n' >> tools/scripts/run_smoke.sh
            printf '  check_dir "$d"\n' >> tools/scripts/run_smoke.sh
            printf 'done\n' >> tools/scripts/run_smoke.sh
            printf 'echo "[smoke] OK"\n' >> tools/scripts/run_smoke.sh
            chmod +x tools/scripts/run_smoke.sh
          fi

      - name: Seed tools/scripts/update_tracker.py if missing
        shell: bash
        run: |
          if [ ! -f tools/scripts/update_tracker.py ]; then
            cat > tools/scripts/update_tracker.py <<'PY'
#!/usr/bin/env python3
import re, pathlib, yaml
ROOT = pathlib.Path(__file__).resolve().parents[2]
TRACKER = ROOT / "docs" / "TRACKER.md"
PROGRESS = ROOT / "docs" / "progress.yaml"
prog = yaml.safe_load(PROGRESS.read_text()) or {}
md = TRACKER.read_text()
def repl(m):
    row = m.group(0)
    cells = [c.strip() for c in row.strip().split("|")[1:-1]]
    if len(cells) < 7:
        return row
    tid = cells[0]
    if tid in prog:
        cells[5] = str(prog[tid])  # % column
        return "| " + " | ".join(cells) + " |\n"
    return row
new = re.sub(r"^\|.*\|\s*$", repl, md, flags=re.M)
if new != md:
    TRACKER.write_text(new)
    print("TRACKER.md updated")
else:
    print("No tracker changes")
PY
            chmod +x tools/scripts/update_tracker.py
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Run smoke
        run: bash tools/scripts/run_smoke.sh

      - name: Update tracker
        run: python tools/scripts/update_tracker.py

      - name: Commit tracker if changed
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/TRACKER.md || true
          git diff --cached --quiet || git commit -m "ci: update TRACKER.md via progress.yaml"
          git push
