name: sanity-smoke
on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/smoke.yml"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo
        run: echo "Actions are working on branch: ${GITHUB_REF}"
